### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by benza86** [ismaeltoe/osms-php#3]
I have this error when i run sendSms.php
API call failed with cURL error: SSL certificate problem: unable to get local issuer certificate

**Comment by ismaeltoe** [comment]
See [https://github.com/ismaeltoe/osms-php#ssl-certificate-problem](https://github.com/ismaeltoe/osms-php#ssl-certificate-problem)

**Comment by benza86** [comment]
thank you,
i put this line to get token? because i have this error now (The requested service needs credentials, but the ones provided were invalid.)

'token' => $osms->getToken()

**Comment by ismaeltoe** [comment]
Yes, you can do that if you already retrieved an access token with `getTokenFromConsumerKey()`.
