### ISSUE TITLE
Does Orange API sms sends messages to Etisalat and Vodafone ?

### ISSUE THREAD

**Issue by heshamabdallah** [ismaeltoe/osms-php#5]
I tried to send an sms to Orange phone number and it was sent successfully! but when i tried to send to Etisalat or Vodafone number there weren't sent and the bundle decreased by two.

does orange API sms sends sms messages to Etisalat and Vodafone ?

Thank you!

**Comment by ismaeltoe** [comment]
I am not sure. You should ask to Orange API managers.

**Comment by abdoulazi** [comment]
Merci pour votre reponse. Mon veritable probleme ce que, je n'arrive mem
pas a integrer votre librarie APi sms orange dans mon site web.
 comment proeder?

https://github.com/ismaeltoe/osms-php

2017-10-01 14:34 GMT+01:00 Ismael Toé <notifications@github.com>:

**Comment by abdoulazi** [comment]
ok merci beaucoup


2017-10-01 16:05 GMT+02:00 Ismael Toé <notifications@github.com>:
