### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by Bileloueslati** [ismaeltoe/osms-php#7]
My API is working !

I have two questions please:

- How to customize sender name ? my sender_name var is set but the receiver got a strange name (SMS09...)

- How to check the balance before sending an SMS ?

**Comment by MohamedSR** [comment]
How to customize sender name ? i got sms name SMS09

**Comment by ismaeltoe** [comment]
To customize the sender name, you have to contact Orange.

**Comment by MohamedSR** [comment]
@Bileloueslati to customize sender name use this link  https://developer.orange.com/?formsrc=SMSqueries
